import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/js/pages/welcome.js',
                'resources/js/pages/welcome-login-perspective.js',
                'resources/js/pages/welcome-hero.js',
                'resources/js/pages/welcome-scroll-reveal.js',
                'resources/js/pages/welcome-editorial-headings.js',
                'resources/js/pages/ppdb-journey.js',
                'resources/js/pages/public-login.js',
                'resources/js/pages/public-auth-perspective.js',
                'resources/js/pages/student-account.js',
                'resources/js/pages/admin-accounts.js',
                'resources/css/pages/welcome-critical.css',
                'resources/css/pages/welcome.css',
                'resources/css/pages/welcome-login-perspective.css',
                'resources/css/pages/welcome-hero.css',
                'resources/css/pages/welcome-home-hero.css',
                'resources/css/pages/welcome-home-type-latin.css',
                'resources/css/pages/welcome-home-type-arabic.css',
                'resources/css/pages/welcome-vision-waapi.css',
                'resources/css/pages/welcome-values-story.css',
                'resources/css/pages/welcome-depth-gallery.css',
                'resources/css/pages/welcome-article-showcase.css',
                'resources/css/pages/welcome-mega-menu.css',
                'resources/css/pages/welcome-scroll-reveal.css',
                'resources/css/pages/welcome-editorial-headings.css',
                'resources/css/pages/welcome-editorial-description-desktop.css',
                'resources/css/pages/ppdb-journey.css',
                'resources/css/pages/public-auth.css',
                'resources/css/pages/public-auth-perspective.css',
                'resources/css/pages/student-dashboard.css',
                'resources/css/pages/admin-accounts.css',
                'resources/css/pages/article-canvas.css',
                'resources/css/pages/article-reader.css',
                'resources/css/text-system.css',
                'resources/css/arabic-typography.css',
                'resources/css/public-latin-inter.css',
                'resources/js/pages/article-canvas.js',
                'resources/js/pages/article-canvas-arabic.js',
                'resources/js/pages/article-canvas-context-ui.js',
                'resources/css/pages/account-locked.css',
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});